changelog:
  repository: mautic/mautic-wordpress
  sections:
    - title: "âœ¨ Enhancements"
      labels: ["enhancement", "feature"]
    - title: "ğŸ Bugs"
      labels: ["bug", "regression"]
  contributors:
    title: "ğŸ’– Contributors"